apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-php
  template:
    metadata:
      labels:
        app: nginx-php
    spec:
      containers:
      - name: nginx-php
        image: omriv/nginx_php7.4-fp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-php-service
spec:
  type: NodePort
  selector:
    app: nginx-php
  ports:
  - name: http
    port: 80
    targetPort: 80
